changed program to programme
nihruk/ioda pull request #49
Opened 2023-04-24 09:24 UTC by AndreaLDavies

2023-05-02 11:20 UTC, mdbudd commented on .idea/.gitignore
> +# Default ignored files
I've done this now but can't help feel that from a project dependency perspective, it'd be good to include in the project `.gitignore` too. I added it in a previous commit so if you merge from main it should be included.

2023-05-10 10:13 UTC, bartfeenstra requested changes

2023-05-10 10:13 UTC, bartfeenstra commented on .idea/.gitignore
> +# Default ignored files
@AndreaLDavies Are these all JetBrains files? Then instead we can put `/.idea` in `.gitignore` in the project root

2023-05-10 10:13 UTC, bartfeenstra commented on .idea/.gitignore
> +# Default ignored files
And then `.idea` should be removed from this PR, and we can merge

2023-05-16 10:52 UTC, closed without merging