IODA-53: Set up Symfony
nihruk/ioda pull request #52
Opened 2023-05-23 13:38 UTC by baldygeezer

This fixes https://nihr-web.atlassian.net/browse/IODA-53

At the moment it builds into the default bare bones symfony app. No controllers or models
There is a simple github workflow that validates the composer file

2023-05-24 11:14 UTC, mdbudd approved these changes

2023-05-24 13:56 UTC, bartfeenstra requested changes

2023-05-24 13:56 UTC, bartfeenstra commented on README.md
> +### Usage Instructions
This section will need to be combined with the `Development` section. Note that for now both PHP and Node.js/npm are needed.

2023-05-25 08:23 UTC, bartfeenstra approved these changes

2023-05-25 08:24 UTC, merged