IODA-124: Content negotiation
nihruk/ioda pull request #59
Opened 2023-06-02 11:29 UTC by mdbudd

2023-06-07 09:43 UTC, bartfeenstra requested changes

2023-06-07 09:43 UTC, bartfeenstra commented on psalm.xml
> +    errorLevel="5"
Which benefits does this looser level deliver us?

2023-06-07 09:43 UTC, bartfeenstra commented on src/EventListener/RequestListener.php
> +            'trace' => \in_array($this->environment, ['dev', 'test'], true) ? $exception->getTrace() : []
Smart to keep that in mind!

2023-06-07 09:43 UTC, bartfeenstra commented on src/EventListener/RequestListener.php
> +            $response->headers->set("Content-Type", $this->accepts);
It's been a while, but I seem to remember that if controllers return `JsonResponse`, the HTTP response content type is included in there. Instead of overriding this (which may be hard to debug if we ever expand the number of supported content types, e.g. for binary files), it may be helpful to error if the `Response`'s content type does not match the one in `$this->accept`?

2023-06-07 09:43 UTC, bartfeenstra commented on src/EventListener/RequestListener.php
> +     * @var array<String>
Yay for generics in modern PHP!

2023-06-07 09:43 UTC, bartfeenstra commented on src/EventListener/RequestListener.php
> +            throw new AccessDeniedHttpException("IODA is only accepting {$accept_string} at present!");
This should be a 406 Not Acceptable.

2023-06-07 10:51 UTC, mdbudd commented on src/EventListener/RequestListener.php
> +            $response->headers->set("Content-Type", $this->accepts);
You could do whatever you like in the controller but I think this is a secure way of enforcing `$this->acceptable` controls the output regardless of that; which I believe was stipulated in the DOD. If you restricted say to `text/html` for any reason you'd then get an error if you tried to output json, for instance.

2023-06-07 10:55 UTC, mdbudd commented on psalm.xml
> +    errorLevel="5"
Don't know, this is unchanged from `main` branch

2023-06-07 11:17 UTC, bartfeenstra commented on src/EventListener/RequestListener.php
> +            $response->headers->set("Content-Type", $this->accepts);
My issue that this can cause confusing runtime problems by ignoring whatever the controller returns. If I understand the code correctly, this can lead to HTTP responses with `Content-Type: application/json` but a body that is something different.

2023-06-08 10:56 UTC, AndreaLDavies approved these changes

2023-06-08 13:16 UTC, baldygeezer approved these changes

2023-06-12 13:09 UTC, merged