IODA-128: Enforce PSR-12
nihruk/ioda pull request #60
Opened 2023-06-05 13:52 UTC by bartfeenstra

2023-06-06 09:53 UTC, mdbudd requested changes

2023-06-06 09:53 UTC, mdbudd commented on composer.json
> +        "test": [
Nice!

2023-06-06 09:53 UTC, mdbudd commented on composer.json
> +            "App\\Tests\\": "tests/src"
Noted, although not default symfony way. Seems like tests naturally sit outside of app but not overly contesting this.

2023-06-06 09:53 UTC, mdbudd commented on phpunit.xml.dist
> +            <directory>tests/src/Integration</directory>
Please see above comment.

2023-06-06 13:49 UTC, bartfeenstra commented on composer.json
> +            "App\\Tests\\": "tests/src"
You're right. Depends on where you put any test assets. I you put them somewhere outside `./tests` then yes. I made the assumption we'd put them in `./tests`, but that can be changed.

2023-06-07 10:59 UTC, baldygeezer approved these changes
I am happy with this. At this stage details about test organisation and directory structure shouldn't be a massive worry. We will probably need to refactor a few times to arrive at an optimal solution as things grow

2023-06-07 13:32 UTC, merged