IODA-60: Generate OpenAPI spec
nihruk/ioda pull request #66
Opened 2023-06-13 14:39 UTC by mdbudd

2023-06-13 15:08 UTC, bartfeenstra commented on composer.json
> +        "symfony/twig-bundle": "6.2.*",
What is Twig being used for here?

2023-06-13 15:10 UTC, mdbudd commented on composer.json
> +        "symfony/twig-bundle": "6.2.*",
A dependency of the openapi spec package

2023-06-13 15:55 UTC, bartfeenstra commented on composer.json
> +        "symfony/twig-bundle": "6.2.*",
We must only declare those packages we use directly as dependencies. If something is a dependency of one of our dependencies, we must not add it ourselves.

2023-06-14 11:19 UTC, bartfeenstra requested changes

2023-06-14 11:19 UTC, bartfeenstra commented on tests/src/Integration/Controller/ContentNegotiationControllerTest.php
> +    public function testOpenApi(): void
This is not a content negotiation test.

2023-06-19 11:57 UTC, bartfeenstra approved these changes

2023-06-19 11:57 UTC, merged