Refine the coding standard
nihruk/ioda pull request #70
Opened 2023-06-13 16:05 UTC by bartfeenstra

2023-06-14 13:48 UTC, baldygeezer requested changes

2023-06-14 13:48 UTC, baldygeezer commented on psalm.xml
> +        <directory name="tests/src"/>
Will we have any testing assets outside of tests/src? Shouldn't these also be scanned?

2023-06-15 07:38 UTC, bartfeenstra commented on psalm.xml
> +        <directory name="tests/src"/>
`tests/src` is for PHP code. Anything outside of it may be for tests but won't be PHP.

2023-06-15 09:49 UTC, baldygeezer approved these changes

2023-06-15 09:50 UTC, merged